name: more_builders
description: A simple package including "builder wrappers" for Rows, Columns and Wraps
version: 0.0.1
author: Tilman Kieselbach
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: